application: axis-tcsiteservices-co-uk
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /css
  static_dir: css

- url: /depots/*
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
